### ISSUE TITLE
GUI not compatible with new obspy taup?

### ISSUE THREAD

**Issue by martinvandriel** [krischer/instaseis#2]
In the GUI, I get these errormsg when traveltimes are switched on:

```
Traceback (most recent call last):
  File "/home/ex/local/src/instaseis/instaseis/gui/instaseis_gui.py", line 611, in on_depth_slider_valueChanged
    self.update()
  File "/home/ex/local/src/instaseis/instaseis/gui/instaseis_gui.py", line 435, in update
    src_depth_in_m / 1000.0, model="ak135")
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/taup.py", line 74, in getTravelTimes
    phase_list=phase_list)
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/tau.py", line 342, in get_travel_times
    tt.run()
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/taup_time.py", line 37, in run
    self.depth_correct(self.depth)
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/taup_time.py", line 49, in depth_correct
    self.recalc_phases()
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/taup_time.py", line 72, in recalc_phases
    self.depth_corrected_model)
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/seismic_phase.py", line 110, in __init__
    self.sum_branches(tMod)
  File "/home/ex/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/taup/seismic_phase.py", line 618, in sum_branches
    self.ray_param = tMod.ray_param.copy()
AttributeError: 'TauModel' object has no attribute 'ray_param'
```

**Comment by krischer** [comment]
I could not reproduce this but I adapted instaseis to use the new `obspy.taup` interface nonetheless.

Maybe some edge case with the compatibility layer for the old `obspy.taup` interface? Maybe we can have another look next time you are in Munich. Please reopen if the issue remains.
